### ISSUE TITLE
Add to Lazysodium's projects page

### ISSUE THREAD

**Issue by gurpreet-** [atholbro/paseto#2]
Hello!

I've just ran a search across GitHub to see projects using Lazysodium, would it be possible to add this project to the [Project's using Lazysodium page](https://docs.lazycode.co/lazysodium/projects)?

Thanks!

**Comment by atholbro** [comment]
Ya for sure.

Right now I'm working on documentation, then I plan to add it to the Paseto list as well.

**Comment by gurpreet-** [comment]
Awesome, I've added it 👍

**Comment by atholbro** [comment]
Thanks!
